export const NAMESPASE = 'nonpay/'
export const CHAT_ROOM_INFO = NAMESPASE + 'CHAT_ROOM_INFO' // ChatRoomInfo
export const GET_CHAT_ROOM_INFO = NAMESPASE + 'GET_CHAT_ROOM_INFO'
export const GET_CHAT_ROOM_ERROR = NAMESPASE + 'GET_CHAT_ROOM_ERROR'
