export const NAMESPACE = 'comment/'
export const GET_COMMENT = NAMESPACE + 'GET_COMMENT' // 获取评论
export const COMMENT = NAMESPACE + 'COMMENT'  // 评论
export const REPLYS = NAMESPACE + 'REPLYS'  // replys 回复
export const ADD_VOTE = NAMESPACE + 'ADD_VOTE' // addVote 添加点赞
export const ADD_SUB_VOTE = NAMESPACE + 'ADD_SUB_VOTE' // addSubVote 给评论点赞
export const ADD_REPLY = NAMESPACE + 'ADD_REPLY'// addReply 添加评论
export const ADD_SUB_REPLY = NAMESPACE + 'ADD_SUB_REPLY' // addSubReply 给评论添加回复
export const ADD_VIEW_NUM = NAMESPACE + 'ADD_VIEW_NUM' // addViewNum 添加浏览数
